server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 9000
  servlet:
    context-path: /emos-wx-api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: aiqilincs4612
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
        additional-exclude: static


  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456
  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username: yangdi525@aliyun.com
    password: ax105105

mybatis-plus:
  configuration:
    cache-enabled: false #禁用二级缓存
    local-cache-scope: statement


# 日志级别
logging:
  level:
    base: info
    # sql 日志
    com.*.dao: debug
    org.springframework.jdbc.core: info

emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10

wx:
  app-id: wxc19fb20b9848c697
  app-secret: 6ed6eafff7dc9167ff45129b0f5efa16

